import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
page.on('pageerror', e => console.log('[pageerror]', e.message))
await page.goto('http://127.0.0.1:8090/')
await page.click('#newbin')
await page.waitForSelector('#binpanel:not([hidden])', { timeout: 5000 })
const binUrl = await page.textContent('#binurl')
console.log('UI created bin URL:', binUrl)
console.log('page url after create:', page.url())
const binId = new URL(page.url()).searchParams.get('bin')
const resp = await fetch('http://127.0.0.1:8080/b/' + binId + '/hook?z=9', {
  method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({via:'playwright'})
})
console.log('capture status:', resp.status)
await page.click('#refresh')
await page.waitForSelector('.req', { timeout: 5000 })
const reqText = (await page.textContent('.req summary')).trim().replace(/\s+/g,' ')
console.log('first request row:', reqText)
await page.click('.req summary')
await page.waitForTimeout(200)
console.log('body shows playwright payload:', (await page.content()).includes('"via": "playwright"') || (await page.content()).includes('playwright'))
await page.goto('http://127.0.0.1:8090/?bin=' + binId)
await page.waitForSelector('.req', { timeout: 5000 })
console.log('deep-link reload rows:', (await page.$$('.req')).length)
await browser.close()
console.log('PLAYWRIGHT OK')
