import pg from 'pg'
const c = new pg.Client({ host:'127.0.0.1', port:5610, user:'postgres', password:'postgres', database:'postgres', ssl:false })
await c.connect()
const repos = await c.query('select did, email, rev from repos')
console.log('repos:', JSON.stringify(repos.rows))
const actors = await c.query('select did, handle from actors')
console.log('actors:', JSON.stringify(actors.rows))
const recs = await c.query("select did, nsid, rkey, cid, length(value) as vlen from records")
console.log('records:', JSON.stringify(recs.rows))
const blk = await c.query('select count(*)::int as n from blocks')
console.log('blocks count:', blk.rows[0].n)
const recCbor = await c.query("select encode(value,'hex') as hx from records limit 1")
const buf = Buffer.from(recCbor.rows[0].hx,'hex')
console.log('record cbor contains text?', buf.includes(Buffer.from('hello from cocoon on zeropg')))
await c.end()
